export const UserRoutes = {
  SIGNUP: "/signup",
  VERIFY_OTP: "/verify-otp",
  LOGIN: "/login",
  GOOGLE_SIGNUP: "/google-signup",
  VERIFY_REESET_OTP: "/verify-reset-otp",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  GET_ALL_DESTINATIONS: "/destinations",
  PROFILE: "/profile",
  GET_SINGLE_DESTINATION: "/destination/:id",
  RESEND_OTP: "/resend-otp",
  GET_ALL_PACKAGES: "/package/:id",
  EDIT_PROFILE: "/profile",
  CREATE_BOOKING: "/create-bookings",
  CREATE_PAYMENT: "/create-payment",
  USER_BOOKINGS: "/bookings",
  REVIEWS: "/create-reviews",
  All_REVIEWS: "/reviews/:id",
  PASSWORD: "/password",
  CANCEL_BOOKING: "/bookings/:id",
  USER_WALLET:'/wallet',
  GET_USER_WALLET:'/wallet/:id',
  BUDDY_PACKAGES:'/buddy-packages',
  JOIN_TRAVEL:'/join-travel/:travelId/:userId',
  BOOKING_BUDDYTRAVEL:'/booking/travel',
  BOOKING_RESHEDULE:'/booking/:id/reschedule',
  WALLET_PAYMENT:'/wallet/payment',
  WALLET_BOOKING:'/wallet/booking',

};
