export const VendorRoutes = {
  SIGNUP: "/signup",
  VERIFY_OTP: "/verify-otp",
  CHECK_STATUS: "/status",
  LOGIN: "/login",
  PROFILE: "/profile",
  GET_DESTINATIONS: "/destinations",
  CREATE_DESTINATION: "/create-destination",
  EDIT_DESTINATION: "/edit/:id",
  DELETE_DESTINATION: "/destination/:id",
  ADD_PACKAGE: "/add-Package",
  ALL_PACKAGES: "/packages",
  EDIT_PACKAGE: "/packages/:id",
  DELET_PACKAGE: "/packages/:id",
  EDIT_PROFILE: "/profile/:id",
  PACKAGE_WISE_GROUPING: "/package-groups",
  PACKAGE_WISE_GROUPS: "/package-group/:id",
  CREATE_HOTEL: "/add-hotel/:id",
  CREATE_ACTIVITY: "/add-activity/:id",
  HOTELS: "/hotels",
  ACTIVITIES: "/activities",
  EDIT_ACTIVITY: "/activities/:id",
  DELETE_ACTIVITY: "/activities/:id",
  EDIT_HOTEL: "/hotels/:id",
  DELETE_HOTEL: "/hotels/:id",
  SEARCH_PACKAGE: "/packages/search",
  SEARCH_HOTEL: "/hotels/search",
  SEARCH_ACTIVITY: "/activities/search",
  CREATE_FLIGHT: "/create-flight",
  ALL_FLIGHTS: "/flights",
  EDIT_FLIGHT: "/flights/:id",
  DELETE_FLIGHT: "/flights/:id",
  USER_BOOKINGS: "/bookings/:id",
  BOOKING_DATES: "/bookings/date/:id",
  SUBSCRIPTION_BOOKING: "/subscription-booking",
  VERIFY_PAYMENT: "/subscription/verify-payment",
  CREATE_BUDDY_TRAVEL:'/create-buddy-travel',
  BUDDY_PACKAGES:'/buddy-packages/:id',
  VENDOR_WALLET:'/wallet',
  GET_VENDOR_WALLET:'/wallet/:id'
};
