export const API_BASE = "/api";
export const ADMIN_BASE = `${API_BASE}/admin`;
export const VENDOR_BASE = `${API_BASE}/vendor`;

// Base routes for easy access
export const ADMIN_ROUTES_BASE = ADMIN_BASE;
export const USER_ROUTES_BASE = API_BASE;
export const VENDOR_ROUTES_BASE = VENDOR_BASE;

export const AdminRoutes = {
    LOGIN: "/login",
    GET_DESTINATIONS: "/destinations",
    CREATE_DESTINATION: "/create-destination",
    EDIT_DESTINATION: "/edit/:id",
    DELETE_DESTINATION: "/destination/:id",
    GET_VENDOR_BY_EMAIL: "/vendors/:email",
    ADMIN_VENDOR_APPROVAL: "/vendors/status/:id",
    GET_ALL_VENDORS: "/vendors",
    GET_VENDOR_BY_STATUS: "/vendors/status/:status",
    BLOCK_UNBLOCK_VENDOR: "/vendors/isBlocked/:id",
    GET_ALL_USERS: "/users",
    UPDATE_USER_STATUS: "/user/status/:id",
    TRAVEL_POSTS_BY_STATUS: "/travel-posts/status/:status",
    TRAVEL_POST_STATUS_UPDATE: "/travel-posts/status/:id",
    CREATE_CATEGORY: "/create-categories",
    EDIT_CATEGORY: "/category/:id",
    GET_ALL_CATEGORIES: "/categories",
    DELETE_CATEGORY: "/category/:id",
    CREATE_BANNER: "/create-banner",
    GET_ALL_BANNERS: "/banner",
    EDIT_BANNER: "/banner/:id",
    DELETE_BANNER: "/banner/:id",
    CREATE_SUBSCRIPTION: "/create-subscription",
    GET_ALL_SUBSCRIPTIONS: "/subscriptions",
    SEARCH_USER: "/user/search",
    SEARCH_VENDOR: "/vendors/search",
    SEARCH_DESTINATION: "/destination/search",
    SEARCH_CATEGORY: "/category/search",
    BANNER_ACTIONS: "/banner/:id",
    EDIT_SUBSCRIPTION: "/subscriptions/:id",
    DELETE_SUBSCRIPTION: "/subscriptions/:id",
    ADMIN_WALLET: "/wallet",
    GET_ADMIN_WALLET: "/wallet/:id",
    TRANSFER_AMOUNT: "/transfer-amount",
    COMPLETED_BOOKINGS: "/completed-bookings",
    NEARBY_LOCATIONS: "/destination/nearby",
    COMPLETED_TRIP: "/complete-trip",
    BOOKED_SUBSCRIPTION: '/booked-subscription',
    GET_ALL_BOOKINGS: '/all-bookings'
};

export const UserRoutes = {
    SIGNUP: "/signup",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    GOOGLE_SIGNUP: "/google-signup",
    VERIFY_REESET_OTP: "/verify-reset-otp",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GET_ALL_DESTINATIONS: "/destinations",
    PROFILE: "/profile",
    GET_SINGLE_DESTINATION: "/destination/:id",
    RESEND_OTP: "/resend-otp",
    GET_ALL_PACKAGES: "/package/:id",
    SEARCH_PACKAGES: "/packages/search",
    EDIT_PROFILE: "/profile",
    CREATE_BOOKING: "/create-bookings",
    CREATE_PAYMENT: "/create-payment",
    USER_BOOKINGS: "/bookings",
    REVIEWS: "/create-reviews",
    All_REVIEWS: "/reviews/:id",
    PASSWORD: "/password",
    CANCEL_BOOKING: "/bookings/:id",
    USER_WALLET: '/wallet',
    GET_USER_WALLET: '/wallet/:id',
    BOOKING_RESHEDULE: '/booking/:id/reschedule',
    WALLET_PAYMENT: '/wallet/payment',
    WALLET_BOOKING: '/wallet/booking',
    NOTIFY: "/notification/notify",
    READ_NOTIFICATION: "/notification/read/:id",
    TRAVEL_POSTS: "/posts",
    TRAVEL_POSTS_MY: "/posts/my",
    TRAVEL_POST_CATEGORIES: "/posts/categories",
    TRAVEL_POST_BY_SLUG: "/posts/:slug",
    TRAVEL_POST_SAVE_TOGGLE: "/posts/:id/save",
    TRAVEL_POST_SAVED: "/posts/saved",
    TRAVEL_POST_TRACK_VIEW: "/posts/:id/view",
    CHAT_SEND: "/chat/send",
    CHAT_MESSAGES: "/chat/messages/:chatId",
    CHAT_LIST: "/chat/:userId",
    CHAT_MARK_SEEN: "/chat/messages/mark-seen",
};

export const VendorRoutes = {
    SIGNUP: "/signup",
    VERIFY_OTP: "/verify-otp",
    CHECK_STATUS: "/status",
    AUTH_STATUS: "/auth-status",
    LOGIN: "/login",
    PROFILE: "/profile",
    GET_DESTINATIONS: "/destinations",
    CREATE_DESTINATION: "/create-destination",
    EDIT_DESTINATION: "/edit/:id",
    DELETE_DESTINATION: "/destination/:id",
    ADD_PACKAGE: "/add-Package",
    ALL_PACKAGES: "/packages",
    EDIT_PACKAGE: "/packages/:id",
    DELET_PACKAGE: "/packages/:id",
    EDIT_PROFILE: "/profile",
    PACKAGE_WISE_GROUPING: "/package-groups",
    PACKAGE_WISE_GROUPS: "/package-group/:id",
    CREATE_HOTEL: "/add-hotel/:id",
    CREATE_ACTIVITY: "/add-activity/:id",
    HOTELS: "/hotels",
    ACTIVITIES: "/activities",
    EDIT_ACTIVITY: "/activities/:id",
    DELETE_ACTIVITY: "/activities/:id",
    EDIT_HOTEL: "/hotels/:id",
    DELETE_HOTEL: "/hotels/:id",
    SEARCH_PACKAGE: "/packages/search",
    SEARCH_HOTEL: "/hotels/search",
    SEARCH_ACTIVITY: "/activities/search",
    CREATE_FLIGHT: "/create-flight",
    ALL_FLIGHTS: "/flights",
    EDIT_FLIGHT: "/flights/:id",
    DELETE_FLIGHT: "/flights/:id",
    USER_BOOKINGS: "/bookings/:id",
    BOOKING_DATES: "/bookings/date/:id",
    SUBSCRIPTION_BOOKING: "/subscription-booking",
    VERIFY_PAYMENT: "/subscription/verify-payment",
    GET_VENDOR_SUBSCRIPTION: "/subscription",
    VENDOR_WALLET: "/wallet",
    GET_VENDOR_WALLET: "/wallet/:id",
    CHAT_SEND: "/chat/send",
    CHAT_MESSAGES: "/chat/messages/:chatId",
    CHAT_LIST: "/chat/:vendorId",
    CHAT_MARK_SEEN: "/chat/messages/mark-seen",
    NOTIFY: "/notification/notify",
    READ_NOTIFICATION: "/notification/read/:id",
    LIST: "/list",
    FORGOT_PASSWORD: "/forgot-password",
};
