export const API_BASE = "/api";
export const ADMIN_BASE = `${API_BASE}/admin`;
export const VENDOR_BASE = `${API_BASE}/vendor`;

// Base routes for easy access
export const ADMIN_ROUTES_BASE = ADMIN_BASE;
export const USER_ROUTES_BASE = API_BASE;
export const VENDOR_ROUTES_BASE = VENDOR_BASE;

export const AdminRoutes = {
    LOGIN: "/login",
    GET_DESTINATIONS: "/destinations",
    CREATE_DESTINATION: "/create-destination",
    EDIT_DESTINATION: "/edit/:destinationId",
    DELETE_DESTINATION: "/destination/:destinationId",
    GET_VENDOR_BY_EMAIL: "/vendors/:email",
    ADMIN_VENDOR_APPROVAL: "/vendors/status/:vendorId",
    GET_ALL_VENDORS: "/vendors",
    GET_VENDOR_BY_STATUS: "/vendors/status/:status",
    BLOCK_UNBLOCK_VENDOR: "/vendors/isBlocked/:vendorId",
    GET_ALL_USERS: "/users",
    UPDATE_USER_STATUS: "/user/status/:userId",
    TRAVEL_POSTS_BY_STATUS: "/travel-posts/status/:status",
    TRAVEL_POST_STATUS_UPDATE: "/travel-posts/status/:postId",
    CREATE_CATEGORY: "/create-categories",
    EDIT_CATEGORY: "/category/:categoryId",
    GET_ALL_CATEGORIES: "/categories",
    DELETE_CATEGORY: "/category/:categoryId",
    CREATE_BANNER: "/create-banner",
    GET_ALL_BANNERS: "/banner",
    EDIT_BANNER: "/banner/:bannerId",
    DELETE_BANNER: "/banner/:bannerId",
    CREATE_SUBSCRIPTION: "/create-subscription",
    GET_ALL_SUBSCRIPTIONS: "/subscriptions",
    SEARCH_USER: "/user/search",
    SEARCH_VENDOR: "/vendors/search",
    SEARCH_DESTINATION: "/destination/search",
    SEARCH_CATEGORY: "/category/search",
    BANNER_ACTIONS: "/banner/:bannerId",
    EDIT_SUBSCRIPTION: "/subscriptions/:subscriptionId",
    DELETE_SUBSCRIPTION: "/subscriptions/:subscriptionId",
    ADMIN_WALLET: "/wallet",
    GET_ADMIN_WALLET: "/wallet/:adminId",
    TRANSFER_AMOUNT: "/transfer-amount",
    COMPLETED_BOOKINGS: "/completed-bookings",
    NEARBY_LOCATIONS: "/destination/nearby",
    COMPLETED_TRIP: "/complete-trip",
    BOOKED_SUBSCRIPTION: '/booked-subscription',
    GET_ALL_BOOKINGS: '/all-bookings'
};

export const UserRoutes = {
    SIGNUP: "/signup",
    VERIFY_OTP: "/verify-otp",
    LOGIN: "/login",
    GOOGLE_SIGNUP: "/google-signup",
    VERIFY_REESET_OTP: "/verify-reset-otp",
    FORGOT_PASSWORD: "/forgot-password",
    RESET_PASSWORD: "/reset-password",
    GET_ALL_DESTINATIONS: "/destinations",
    PROFILE: "/profile",
    GET_SINGLE_DESTINATION: "/destination/:destinationId",
    RESEND_OTP: "/resend-otp",
    GET_ALL_PACKAGES: "/package/:destinationId",
    SEARCH_PACKAGES: "/packages/search",
    EDIT_PROFILE: "/profile",
    CREATE_BOOKING: "/create-bookings",
    CREATE_PAYMENT: "/create-payment",
    USER_BOOKINGS: "/bookings",
    REVIEWS: "/create-reviews",
    All_REVIEWS: "/reviews/:packageId",
    PASSWORD: "/password",
    CANCEL_BOOKING: "/bookings/:bookingId",
    USER_WALLET: '/wallet',
    GET_USER_WALLET: '/wallet/:userId',
    BOOKING_RESHEDULE: '/booking/:bookingId/reschedule',
    WALLET_PAYMENT: '/wallet/payment',
    WALLET_BOOKING: '/wallet/booking',
    NOTIFY: "/notification/notify",
    READ_NOTIFICATION: "/notification/read/:notificationId",
    TRAVEL_POSTS: "/posts",
    TRAVEL_POSTS_MY: "/posts/my",
    TRAVEL_POST_CATEGORIES: "/posts/categories",
    TRAVEL_POST_BY_SLUG: "/posts/:slug",
    TRAVEL_POST_SAVE_TOGGLE: "/posts/:postId/save",
    TRAVEL_POST_SAVED: "/posts/saved",
    TRAVEL_POST_TRACK_VIEW: "/posts/:postId/view",
    CHAT_SEND: "/chat/send",
    CHAT_MESSAGES: "/chat/messages/:chatId",
    CHAT_LIST: "/chat/:userId",
    CHAT_MARK_SEEN: "/chat/messages/mark-seen",
};

export const VendorRoutes = {
    SIGNUP: "/signup",
    VERIFY_OTP: "/verify-otp",
    CHECK_STATUS: "/status",
    AUTH_STATUS: "/auth-status",
    LOGIN: "/login",
    PROFILE: "/profile",
    GET_DESTINATIONS: "/destinations",
    CREATE_DESTINATION: "/create-destination",
    EDIT_DESTINATION: "/edit/:destinationId",
    DELETE_DESTINATION: "/destination/:destinationId",
    ADD_PACKAGE: "/add-Package",
    ALL_PACKAGES: "/packages",
    EDIT_PACKAGE: "/packages/:packageId",
    DELET_PACKAGE: "/packages/:packageId",
    EDIT_PROFILE: "/profile",
    PACKAGE_WISE_GROUPING: "/package-groups",
    PACKAGE_WISE_GROUPS: "/package-group/:packageId",
    CREATE_HOTEL: "/add-hotel/:packageId",
    CREATE_ACTIVITY: "/add-activity/:packageId",
    HOTELS: "/hotels",
    ACTIVITIES: "/activities",
    EDIT_ACTIVITY: "/activities/:activityId",
    DELETE_ACTIVITY: "/activities/:activityId",
    EDIT_HOTEL: "/hotels/:hotelId",
    DELETE_HOTEL: "/hotels/:hotelId",
    SEARCH_PACKAGE: "/packages/search",
    SEARCH_HOTEL: "/hotels/search",
    SEARCH_ACTIVITY: "/activities/search",
    CREATE_FLIGHT: "/create-flight",
    ALL_FLIGHTS: "/flights",
    EDIT_FLIGHT: "/flights/:flightId",
    DELETE_FLIGHT: "/flights/:flightId",
    USER_BOOKINGS: "/bookings/:vendorId",
    BOOKING_DATES: "/bookings/date/:vendorId",
    SUBSCRIPTION_BOOKING: "/subscription-booking",
    VERIFY_PAYMENT: "/subscription/verify-payment",
    GET_VENDOR_SUBSCRIPTION: "/subscription",
    VENDOR_WALLET: "/wallet",
    GET_VENDOR_WALLET: "/wallet/:vendorId",
    CHAT_SEND: "/chat/send",
    CHAT_MESSAGES: "/chat/messages/:chatId",
    CHAT_LIST: "/chat/:vendorId",
    CHAT_MARK_SEEN: "/chat/messages/mark-seen",
    NOTIFY: "/notification/notify",
    READ_NOTIFICATION: "/notification/read/:notificationId",
    LIST: "/list",
    FORGOT_PASSWORD: "/forgot-password",
};
